FROM nginx:latest
RUN rm /etc/nginx/conf.d/default.conf

# if SERVICE_TAG is dev then copy the dev config
ARG NGINX_FILE
COPY ./nginx/conf.d/$NGINX_FILE /etc/nginx/conf.d/$NGINX_FILE

# Copie tudo para /var/www menos o diretório vendor
COPY ./public /var/www/public
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]