version: "3.1"

services:
  mysql:
    image: mysql:latest
    container_name: database_go_ing
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ers123
      MYSQL_DATABASE: go-ingressos-dev
      MYSQL_USER: esiqueira
      MYSQL_PASSWORD: ers123
    ports:
      - "3306:3306"

  mysql_stock:
    image: mysql:latest
    container_name: database_go_ing_stock
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ers123
      MYSQL_DATABASE: go-ingressos-stock-dev
      MYSQL_USER: esiqueira
      MYSQL_PASSWORD: ers123
    ports:
      - "3307:3306"
